[package]
name = "llamaedge"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2"
url = "2.5.4"
endpoints = "0.23.0"
reqwest = { version = "0.12.0", features = ["json", "stream"] }
futures = { version = "0.3.6", default-features = false, features = ["async-await", "std"] }
serde_json = "1.0.134"

[dev-dependencies]
tokio = { version = "1.39.0", features = ["full"] }
